module.exports = {
  CLOUD_NAME: process.env.CLOUD_NAME,
  API_KEY_CLOUDINARY: process.env.API_KEY_CLOUDINARY,
  API_SECRET_CLOUDINARY: process.env.API_SECRET_CLOUDINARY,
  CLOUDINARY_ENV_VARIABLE: process.env.CLOUDINARY_ENV_VARIABLE,
  DB_URL: process.env.DB_URL,
  PORT: process.env.PORT,
};
